##################
##  TRANSPORTS  ## -- 27 sur 27
##################

-- Encodage
SET NAMES utf8;

-- Mise à jour des traductions
UPDATE `transports` SET `name` = 'Fossoyeuse, Clairières de Tirisfal et Camp de base Grom’gol, Vallée de Strangleronce' WHERE `guid` = 1;
UPDATE `transports` SET `name` = 'Port d’Hurlevent et Auberdine, Sombrivage' WHERE `guid` = 2;
UPDATE `transports` SET `name` = 'Port de Menethil, Les Paluns et l’île de Theramore, Marécage Marsh' WHERE `guid` = 4;
UPDATE `transports` SET `name` = 'Orgrimmar, Durotar et Camp de base Grom’gol, Vallée de Strangleronce' WHERE `guid` = 5;
UPDATE `transports` SET `name` = 'Orgrimmar, Durotar et Fossoyeuse, Clairières de Tirisfal' WHERE `guid` = 6;
UPDATE `transports` SET `name` = 'Ports Cartel Gentepression, Cabestan et Baie-du-butin' WHERE `guid` = 7;
UPDATE `transports` SET `name` = 'La côte oubliée, Feralas et Bastion de Pennelune, L’île de Sardor, Féralas' WHERE `guid` = 8;
UPDATE `transports` SET `name` = 'Amarrage de Valaar, L’île de Brume-azur et Auberdine, Sombrivage' WHERE `guid` = 9;
UPDATE `transports` SET `name` = 'Port de Menethil, Les Paluns et Valgarde, Fjord Hurlant - Northspear' WHERE `guid` = 10;
UPDATE `transports` SET `name` = 'Fossoyeuse, Clairières de Tirisfal et Accostage de la Vengeance, Fjord Hurlant' WHERE `guid` = 11;
UPDATE `transports` SET `name` = 'Orgrimmar, Durotar et Bastion Chanteguerre, Toundra Boréenne' WHERE `guid` = 12;
UPDATE `transports` SET `name` = 'Garde de l’ouest protège le Fjord Hurlant des bombardements pirate' WHERE `guid` = 13;
UPDATE `transports` SET `name` = 'Cyclisme dans le Fjord Hurlant' WHERE `guid` = 14;
UPDATE `transports` SET `name` = 'Unu’pe, Toundra Boréenne et Port Moa’ki, Désolation des dragons' WHERE `guid` = 15;
UPDATE `transports` SET `name` = 'Port Moa’ki et Kamagua' WHERE `guid` = 16;
UPDATE `transports` SET `name` = 'Port d’Hurlevent et Donjon de la Bravoure, Toundra Boréenne' WHERE `guid` = 17;
UPDATE `transports` SET `name` = 'Patrouilles canonnières de la Horde, La Couronne de glace' WHERE `guid` = 18;
UPDATE `transports` SET `name` = 'Patrouilles canonnières de l’Alliance, La Couronne de glace' WHERE `guid` = 19;
UPDATE `transports` SET `name` = 'Orgrimmar et Les Pitons-du-Tonnerre' WHERE `guid` = 20;
UPDATE `transports` SET `name` = 'Kraazar à Port Gueule-de-dragon' WHERE `guid` = 21;
UPDATE `transports` SET `name` = 'Port Gueule-de-dragon à Kraazar' WHERE `guid` = 22;
UPDATE `transports` SET `name` = 'Navire pour Vashj’ir - Horde' WHERE `guid` = 23;
UPDATE `transports` SET `name` = 'La Lance de Durotar' WHERE `guid` = 24;
UPDATE `transports` SET `name` = 'Navire pour Vashj’ir - Alliance' WHERE `guid` = 25;
UPDATE `transports` SET `name` = 'Zeppelin d’attaque du Kraazar' WHERE `guid` = 26;
UPDATE `transports` SET `name` = 'Le Tréfonds - Canonniers de l’Alliance' WHERE `guid` = 27;
UPDATE `transports` SET `name` = 'Zone Worgen - Canonniers Orcs' WHERE `guid` = 28;