######################
##  QUEST_GREETING  ## -- 64 sur 83
######################

-- Encodage
SET NAMES utf8;

-- Mise à jour des traductions
UPDATE `quest_greeting` SET `Greeting` = 'Une hache que l’on brandit, le cri de guerre de vos alliés, des gouttes de sang sur votre visage. C’est de ça dont un guerrier a besoin, $n. Je vais tailler la lande à la pointe de mon épée, au nom de la Horde.' WHERE `ID` = 3337;
UPDATE `quest_greeting` SET `Greeting` = 'Commandant $n, les informations suivantes requièrent votre attention.' WHERE `ID` = 232400;
UPDATE `quest_greeting` SET `Greeting` = 'La Vallée des épreuves transforme même les plus faibles en guerriers dignes de rejoindre la Horde. Ceux qui n’arrivent pas à surmonter ce qu’elle leur impose pourrissent au soleil.' WHERE `ID` = 3143;
UPDATE `quest_greeting` SET `Greeting` = 'Tout bien considéré, j’espère que vous allez bien.$B$BAsseyez-vous un instant et écoutez mon histoire. C’est une tragédie, bien sûr, mais une tragédie qui, je l’espère, appellera une revanche !' WHERE `ID` = 1500;
UPDATE `quest_greeting` SET `Greeting` = 'La Croisade écarlate arrive sur notre territoire. Ces fanatiques arriérés ne se rendent pas compte que les loyaux serviteurs de la Dame noire vont les détruire.' WHERE `ID` = 1515;
UPDATE `quest_greeting` SET `Greeting` = 'Baine Sabot-de-Sang, notre grand chef, se tenait autrefois ici même et veillait sur ce village, qui porte le nom de son clan.' WHERE `ID` = 36644;
UPDATE `quest_greeting` SET `Greeting` = 'ON RECHERCHE :' WHERE `ID` = 203733;
UPDATE `quest_greeting` SET `Greeting` = 'Bonjour, $gcitoyen:citoyenne;. Vous semblez avoir un but précis. Ce dernier est-il en rapport avec l’armée de Hurlevent ?' WHERE `ID` = 261;
UPDATE `quest_greeting` SET `Greeting` = 'Faites gaffe où vous mettez les pieds, bleusaille.' WHERE `ID` = 42308;
UPDATE `quest_greeting` SET `Greeting` = 'Salut à vous. Je suis Remy. Je viens des Carmines, à l’est, et je suis venu jusqu’ici pour chercher du travail, chercher du travail. Vous avez quelque chose… Quelque chose ?' WHERE `ID` = 241;
UPDATE `quest_greeting` SET `Greeting` = 'La Croisade écarlate arrive sur notre territoire. Ces fanatiques arriérés ne se rendent pas compte que les loyaux serviteurs de la Dame noire vont les détruire.' WHERE `ID` = 1515;
UPDATE `quest_greeting` SET `Greeting` = 'Oui ?' WHERE `ID` = 48069;
UPDATE `quest_greeting` SET `Greeting` = 'pour la horde' WHERE `ID` = 48360;
UPDATE `quest_greeting` SET `Greeting` = 'Des avis de recherche peu élaborés sont cloués sur ce panneau en bois.' WHERE `ID` = 2713;
UPDATE `quest_greeting` SET `Greeting` = 'Salut, $c ! Je suis Torren Gueule-carrée, le cartographe en chef de la filiale de Thelsamar de la ligue des Explorateurs. C’est impressionnant, non ? Des cartes ! Des cartes ! Je les adore, elles sont ma vie et ma passion.' WHERE `ID` = 1153;
UPDATE `quest_greeting` SET `Greeting` = 'Vous leur avez donné une bonne leçon, commandant, pas vrai ?' WHERE `ID` = 85130;
UPDATE `quest_greeting` SET `Greeting` = 'Cette naine n’est pas sortie vivante de l’Enchevêtrement, mais elle a laissé son journal.' WHERE `ID` = 82569;
UPDATE `quest_greeting` SET `Greeting` =  'Y a plein de bois en Gorgrond. Mais il en faut toujours plus.' WHERE `ID` = 82575;
UPDATE `quest_greeting` SET `Greeting` = 'Ces fichus botani m’engraissaient simplement pour me transformer en compost. J’en reviens pas.$b$bJ’y connais pas grand-chose en agriculture, mais j’imagine qu’il y a mieux pour nourrir une plante.' WHERE `ID` = 81601;
UPDATE `quest_greeting` SET `Greeting` = 'Tout est d’ma faute. J’ai donné à ces nains les coordonnées de l’endroit d’où je pensais qu’ils auraient un bon point d’écoute sur les orcs rochenoires.$b$bJ’avais pas réalisé à quel point les indigènes pouvaient perturber la navigation de la taupe mécanique.' WHERE `ID` = 81588;
UPDATE `quest_greeting` SET `Greeting` = 'Mais voilà $gun jeune et puissant:une jeune et puissante:c; $c ! Vous êtes sans doute là pour entendre mes exploits sur les champs de bataille !$B$BMais pas le temps de raconter ces vieilles histoires, car des affaires urgentes attendent ! Si vous recherchez la gloire, c’est votre jour de chance ...' WHERE `ID` = 1343;
UPDATE `quest_greeting` SET `Greeting` = 'Les Carmines sont en proie au chaos !' WHERE `ID` = 344;
UPDATE `quest_greeting` SET `Greeting` = 'Surveillez vos arrières, $n. Les nervis et les mercenaires rôdent dans les ombres.' WHERE `ID` = 42425;
UPDATE `quest_greeting` SET `Greeting` = 'Pour quelle raison vous présentez-vous devant le tribunal de Comté-du-lac et devant l’honorable magistrat Salomon ?' WHERE `ID` = 900;
UPDATE `quest_greeting` SET `Greeting` = 'Aha ! Bonjour, bonjour, $c ! Venez, entrez prendre un verre. Je vois à vos yeux que vous cherchez de l’occupation et je pense que vous ne perdrez pas votre temps à m’écouter…' WHERE `ID` = 253;
UPDATE `quest_greeting` SET `Greeting` = 'Ne vous inquiétez pas, $r. Je suis mort depuis longtemps, mais je n’ai pas l’intention de vous faire du mal. J’ai été le témoin de trop de morts en mon temps. À présent, mon seul souhait est la paix. Peut-être pourriez-vous m’aider dans ma quête.' WHERE `ID` = 392;
UPDATE `quest_greeting` SET `Greeting` = 'Avec le temps, j’ai appris qu’aucune mission n’était ennuyeuse. Protéger le viaduc de Thandol aurait dû être une tâche facile. Mais comme le gros de l’armée se bat avec l’Alliance, on s’est fait écraser et Dun Modr est tombé.' WHERE `ID` = 1071;
UPDATE `quest_greeting` SET `Greeting` = 'Repos, $c. Si vous ne faites que passer, je vous suggère de bien rester sur les routes et de ne voyager que de jour. Si vous voulez trouver du travail à Sombre-comté, vous devriez vous mettre au service des Veilleurs. Nos compétences sont incontestables, mais nos effectifs sont insuffisants.' WHERE `ID` = 264;
UPDATE `quest_greeting` SET `Greeting` = 'Bonjour, bonjour ! Bienvenue dans ma cuisine, $gmonsieur:madame; ! C’est ici que sont préparés les mets les plus délicats de la taverne du Corbeau écarlate. Ah, sentez ce fumet divin !' WHERE `ID` = 272;
UPDATE `quest_greeting` SET `Greeting` = 'N’oubliez jamais ce que vous avez à gagner, $r.' WHERE `ID` = 464;
UPDATE `quest_greeting` SET `Greeting` = 'La Horde de Fer est une plaie pour ces terres !' WHERE `ID` = 75127;
UPDATE `quest_greeting` SET `Greeting` = 'Notre seul espoir est de rendre positive une situation très négative.' WHERE `ID` = 5767;
UPDATE `quest_greeting` SET `Greeting` = 'Pas de formalités entre nous, $r. Avec les forces de l’Alliance qui sont attaquées, la protection des territoires des nains est particulièrement critique. La révolte des troggs représente une nouvelle menace, et des plus redoutables, pour les terres du roi.' WHERE `ID` = 1092;
UPDATE `quest_greeting` SET `Greeting` = 'Les troggs ! Je jure que les dieux les ont mis sur cette terre uniquement dans le but de me torturer ! On descend quatre pouces plus bas dans les mines, puis on fait deux pas en arrière à cause de troggs !' WHERE `ID` = 1254;
UPDATE `quest_greeting` SET `Greeting` = 'La mission des estafettes consiste à assurer la sécurité des voyageurs qui traversent les plaines de Mulgore. Ceux qui menacent la sécurité des terres des taurens sont punis de nos mains.' WHERE `ID` = 2988;
UPDATE `quest_greeting` SET `Greeting` = 'Il en aura fallu du travail, pour monter jusqu’ici...' WHERE `ID` = 81144;
UPDATE `quest_greeting` SET `Greeting` = 'Parlez, $gmortel:mortelle;. Le dieu corbeau vous écoute.' WHERE `ID` = 80648;
UPDATE `quest_greeting` SET `Greeting` = 'Je pourrais essayer de fixer une fusée à gauche…' WHERE `ID` = 82788;
UPDATE `quest_greeting` SET `Greeting` = 'J’ai dû oublier de l’emporter…' WHERE `ID` = 82759;
UPDATE `quest_greeting` SET `Greeting` = 'Parlez, $gmortel:mortelle;. Le dieu corbeau vous écoute.' WHERE `ID` = 86355;
UPDATE `quest_greeting` SET `Greeting` = 'Les esprits d’Auchindoun s’agitent. Les ténèbres sont toutes proches.' WHERE `ID` = 75392;
UPDATE `quest_greeting` SET `Greeting` = 'Les ombres s’agitent.' WHERE `ID` = 80508;
UPDATE `quest_greeting` SET `Greeting` = 'À votre service, $n.' WHERE `ID` = 80260;
UPDATE `quest_greeting` SET `Greeting` = 'À votre service, $n.' WHERE `ID` = 79392;
UPDATE `quest_greeting` SET `Greeting` = 'La Lumière appelle à l’aide.' WHERE `ID` = 75119;
UPDATE `quest_greeting` SET `Greeting` = 'À votre service, $n.' WHERE `ID` = 80608;
UPDATE `quest_greeting` SET `Greeting` = 'C’est trop tard. Aruuna est perdue.' WHERE `ID` = 75896;
UPDATE `quest_greeting` SET `Greeting` = 'Cette affiche énumère toutes les primes offertes par les habitants de Port-Austral.' WHERE `ID` = 233100;
UPDATE `quest_greeting` SET `Greeting` = 'À votre service, $n.' WHERE `ID` = 80617;
UPDATE `quest_greeting` SET `Greeting` = 'Voir n’est pas croire, en vérité.' WHERE `ID` = 80157;
UPDATE `quest_greeting` SET `Greeting` = 'Merci. Nous n’aurions jamais pu nous échapper sans votre aide.' WHERE `ID` = 75913;
UPDATE `quest_greeting` SET `Greeting` = 'Je n’aurai plus jamais chaud…' WHERE `ID` = 10926;
UPDATE `quest_greeting` SET `Greeting` = 'Commandant, quel plaisir de vous voir !' WHERE `ID` = 91196;
UPDATE `quest_greeting` SET `Greeting` = 'Le combat pour Gnomeregan approche !' WHERE `ID` = 6577;
UPDATE `quest_greeting` SET `Greeting` = 'Ces affreux vieux félins ! Regardez ce qu’ils ont fait !' WHERE `ID` = 76826;
UPDATE `quest_greeting` SET `Greeting` = 'J’attendais votre venue, $gaventurier:aventurière;.' WHERE `ID` = 76665;
UPDATE `quest_greeting` SET `Greeting` = 'Commandant, quel plaisir de vous voir !' WHERE `ID` = 89763;
UPDATE `quest_greeting` SET `Greeting` = 'Certains disent que le marais est maléfique… maléfique…' WHERE `ID` = 4792;
UPDATE `quest_greeting` SET `Greeting` = 'Orneval est une forêt luxuriante, débordante de vie. C’est agréable d’emprunter ses sentiers secrets à la recherche d’herbes, mais il faut prendre garde. La forêt n’est pas sans danger.' WHERE `ID` = 3847;
UPDATE `quest_greeting` SET `Greeting` = 'Je vous salue, $gcitoyen:citoyenne;.' WHERE `ID` = 42256;
UPDATE `quest_greeting` SET `Greeting` = 'Ma beauté perdue me rend la vie insupportable !' WHERE `ID` = 302;
UPDATE `quest_greeting` SET `Greeting` = 'le seigneur Harris m’envoie récupérer des composants. Notre travail ne peut pas prendre de retard…' WHERE `ID` = 43738;
UPDATE `quest_greeting` SET `Greeting` = '<Une voix beugle depuis l’intérieur du totem en bois>$B$BVous vous trouvez devant le puissant Ruumbo !' WHERE `ID` = 206585;
