SET NAMES utf8;

UPDATE `game_event` SET `description` = 'Solstice d\'été : la fête du Feu' WHERE `entry` = 1;
UPDATE `game_event` SET `description` = 'La fête du Voile d\'hiver' WHERE `entry` = 2;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Forêt de Terrokar)' WHERE `entry` = 3;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Elwynn)' WHERE `entry` = 4;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Mulgore)' WHERE `entry` = 5;
UPDATE `game_event` SET `description` = 'Le nouvel an' WHERE `entry` = 6;
UPDATE `game_event` SET `description` = 'La fête lunaire' WHERE `entry` = 7;
UPDATE `game_event` SET `description` = 'De l\'amour dans l\'air' WHERE `entry` = 8;
UPDATE `game_event` SET `description` = 'Le jardin des nobles' WHERE `entry` = 9;
UPDATE `game_event` SET `description` = 'La semaine des enfants' WHERE `entry` = 10;
UPDATE `game_event` SET `description` = 'La fête des moissons' WHERE `entry` = 11;
UPDATE `game_event` SET `description` = 'La Sanssaint' WHERE `entry` = 12;
UPDATE `game_event` SET `description` = 'L\'effort de guerre d\'Ahn Qiraj' WHERE `entry` = 22;
UPDATE `game_event` SET `description` = 'L\'invasion du fléau' WHERE `entry` = 17;
UPDATE `game_event` SET `description` = 'Invasions d\'élémentaux' WHERE `entry` = 13;
UPDATE `game_event` SET `description` = 'Annonce du concours de pêche de Strangleronce' WHERE `entry` = 14;
UPDATE `game_event` SET `description` = 'Le coffre pirate de Gurubashi' WHERE `entry` = 16;
UPDATE `game_event` SET `description` = 'Concours de pêche de Strangleronce' WHERE `entry` = 15;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : vallée d\'Alterac !' WHERE `entry` = 18;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : goulet des Chanteguerres !' WHERE `entry` = 19;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : bassin d\'Arathi !' WHERE `entry` = 20;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : l\'Œil du cyclone !' WHERE `entry` = 21;
UPDATE `game_event` SET `description` = 'La foire de Sombrelune (Elwynn)' WHERE `entry` = 23;
UPDATE `game_event` SET `description` = 'Attaque des loups : Orgrimmar !' WHERE `entry` = 24;
UPDATE `game_event` SET `description` = 'L\'Appel des armes' WHERE `entry` = 25;
UPDATE `game_event` SET `description` = 'La fête des Brasseurs' WHERE `entry` = 26;
UPDATE `game_event` SET `description` = 'Nuit' WHERE `entry` = 27;
UPDATE `game_event` SET `description` = 'Le jardin des nobles' WHERE `entry` = 28;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Gri\'lek' WHERE `entry` = 29;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Hazza\'rah' WHERE `entry` = 30;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Renataki' WHERE `entry` = 31;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Wushoolay' WHERE `entry` = 32;
UPDATE `game_event` SET `description` = 'Tournoi de l\'arène' WHERE `entry` = 33;
UPDATE `game_event` SET `description` = 'Concert des L70ETC' WHERE `entry` = 34;
UPDATE `game_event` SET `description` = 'Le jour des Morts' WHERE `entry` = 35;
UPDATE `game_event` SET `description` = 'Concours de pêche de Strangleronce (Turn-in)' WHERE `entry` = 36;
UPDATE `game_event` SET `description` = 'Bienfaits du pèlerin' WHERE `entry` = 37;
UPDATE `game_event` SET `description` = 'L\'antre de la folie, Wushoolay' WHERE `entry` = 38;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 2b - Activating the Sunwell Portal' WHERE `entry` = 39;
UPDATE `game_event` SET `description` = 'Le jour des morts' WHERE `entry` = 40;
UPDATE `game_event` SET `description` = 'Bienfaits du pélerin' WHERE `entry` = 41;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : l\'île des Conquérants!' WHERE `entry` = 42;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 3b - Rebuilding the Anvil and Forge' WHERE `entry` = 43;
UPDATE `game_event` SET `description` = 'Attaque des démons : Thrallmar !' WHERE `entry` = 44;
UPDATE `game_event` SET `description` = 'Tournoi de pêche kalu\'ak' WHERE `entry` = 45;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 4A - Creating the Alchemy Lab COMPLETE' WHERE `entry` = 46;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 4B - Building the Monument to the Fallen' WHERE `entry` = 47;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 4B - Building the Monument to the Fallen COMPLETE' WHERE `entry` = 48;
UPDATE `game_event` SET `description` = 'L\'Offensive du Puit de Soleil: Phase 4 - COMPLETE' WHERE `entry` = 49;
UPDATE `game_event` SET `description` = 'Janvier' WHERE `entry` = 50;
UPDATE `game_event` SET `description` = 'Février' WHERE `entry` = 51;
UPDATE `game_event` SET `description` = 'Mars' WHERE `entry` = 52;
UPDATE `game_event` SET `description` = 'Avril' WHERE `entry` = 53;
UPDATE `game_event` SET `description` = 'Mai' WHERE `entry` = 54;
UPDATE `game_event` SET `description` = 'Juin' WHERE `entry` = 55;
UPDATE `game_event` SET `description` = 'Juillet' WHERE `entry` = 56;
UPDATE `game_event` SET `description` = 'Août' WHERE `entry` = 57;
UPDATE `game_event` SET `description` = 'Septembre' WHERE `entry` = 58;
UPDATE `game_event` SET `description` = 'Octobre' WHERE `entry` = 59;
UPDATE `game_event` SET `description` = 'Novembre' WHERE `entry` = 60;
UPDATE `game_event` SET `description` = 'Décembre' WHERE `entry` = 61;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Exarch\'s Soul Gem' WHERE `entry` = 100;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Nazan\'s Riding Crop' WHERE `entry` = 101;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Shaffar\'s Wondrous Pendant' WHERE `entry` = 102;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Epoch Hunter\'s Head' WHERE `entry` = 103;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Headfeathers of Ikiss' WHERE `entry` = 104;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Murmur\'s Whisper' WHERE `entry` = 105;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Scroll of Skyriss' WHERE `entry` = 106;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Keli\'dan\'s Feathered Stave' WHERE `entry` = 107;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Pathaleon\'s Projector' WHERE `entry` = 108;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Heart of Quagmirran' WHERE `entry` = 109;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Warlord\'s Treatise' WHERE `entry` = 110;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: A Black Stalker Egg' WHERE `entry` = 111;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Aeonus\'s Hourglass' WHERE `entry` = 112;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: A Warp Splinter Clipping' WHERE `entry` = 113;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Bladefist\'s Seal' WHERE `entry` = 114;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: The Signet Ring of Prince Kael\'thas ' WHERE `entry` = 115;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Coilfang Myrmidons' WHERE `entry` = 116;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Shattered Hand Centurions' WHERE `entry` = 117;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Tempest-Forge Destroyers' WHERE `entry` = 118;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Sunseeker Channelers' WHERE `entry` = 119;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Rift Lords' WHERE `entry` = 120;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Arcatraz Sentinels' WHERE `entry` = 121;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Malicious Instructors' WHERE `entry` = 122;
UPDATE `game_event` SET `description` = 'ON RECHERCHE: Sisters of Torment' WHERE `entry` = 123;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : Le Rivage des Anciens!' WHERE `entry` = 124;
UPDATE `game_event` SET `description` = 'Arênes Saison 3' WHERE `entry` = 126;
UPDATE `game_event` SET `description` = 'Arênes Saison 4' WHERE `entry` = 127;
UPDATE `game_event` SET `description` = 'Arênes Saison 5' WHERE `entry` = 128;
UPDATE `game_event` SET `description` = 'Arênes Saison 6' WHERE `entry` = 129;
UPDATE `game_event` SET `description` = 'Arênes Saison 7' WHERE `entry` = 130;
UPDATE `game_event` SET `description` = 'Arênes Saison 8' WHERE `entry` = 131;
UPDATE `game_event` SET `description` = 'L\'appel aux armes : l\'île des Conquérants!' WHERE `entry` = 125;
