/*
* Herakion.sql
*
*
* Created by Dr.Cheasterfield on 09/07/09.
* Copyright 2009 Herakion. All rights reserved.
*/


/* On fait des mises à jours sur certains PNJ dont nous aurons besoin */
UPDATE `creature_proto` SET maxhealth='6309250' WHERE entry='3057' ;
UPDATE `creature_proto` SET minhealth='3309250' WHERE entry='3057' ;
UPDATE `creature_proto` SET maxlevel='83' WHERE entry='3057' ;
UPDATE `creature_proto` SET maxlevel='81' WHERE entry='3057' ;
UPDATE `creature_proto` SET mindamage = "9000" WHERE entry = "3057" ;
UPDATE `creature_proto` SET maxdamage = "14000" WHERE entry = "3057" ;
/* UPDATE `creature_proto` SET faction = "ID_Guilde2" WHERE entry = "3057" ; */
UPDATE `creature_proto` SET maxhealth='3103250' WHERE entry='7999' ;
UPDATE `creature_proto` SET minhealth='3103250' WHERE entry='7999' ;
UPDATE `creature_proto` SET maxlevel='83' WHERE entry='7999' ;
UPDATE `creature_proto` SET minlevel='81' WHERE entry='7999' ;
UPDATE `creature_proto` SET mindamage = "6000" WHERE entry = "7999" ;
UPDATE `creature_proto` SET maxdamage = "11000" WHERE entry = "7999" ;
/* UPDATE `creature_proto` SET faction = "ID_Guilde3" WHERE entry = "7999" ; */
UPDATE `creature_proto` SET maxhealth='1103250' WHERE entry='2425' ;
UPDATE `creature_proto` SET minhealth='900000' WHERE entry='2425' ;
UPDATE `creature_proto` SET maxlevel='83' WHERE entry='2425' ;
UPDATE `creature_proto` SET minlevel='81' WHERE entry='2425' ;
UPDATE `creature_proto` SET mindamage = "5000" WHERE entry = "2425" ;
UPDATE `creature_proto` SET maxdamage = "10000" WHERE entry = "2425" ;
/* UPDATE `creature_proto` SET faction = "ID_Guilde1" WHERE entry = "2425" ;
UPDATE `creature_proto` SET faction = "ID_Guilde1" WHERE entry = "10181" ; */


/* On fait une cvérifiaction pour éviter que le script existe 2 fois */
DELETE FROM creature_names WHERE entry = "200001" ;
DELETE FROM creature_names WHERE entry = "200002" ;
DELETE FROM creature_names WHERE entry = "200003" ;
DELETE FROM creature_names WHERE entry = "200004" ;
DELETE FROM creature_names WHERE entry = "200005" ;
DELETE FROM creature_names WHERE entry = "200006" ;
DELETE FROM creature_names WHERE entry = "200007" ;
DELETE FROM creature_names WHERE entry = "200008" ;
DELETE FROM creature_names WHERE entry = "200009" ;
DELETE FROM creature_names WHERE entry = "200010" ;
DELETE FROM creature_names WHERE entry = "200011" ;
DELETE FROM creature_names WHERE entry = "200012" ;

/* On insert les PNJ */
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Druide Farouche', 'Invocation de Cairne', '', '7', '0', '1', '3001', '8356', '3001', '8356', '0', NULL, '200004');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '80', '1684', '75000', '90000', '100000', '1', '0', '1500', '0', '4678', '9843', '0', '0', '0', '36000', '150000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '6130', '0', '0', '2.5', '8', '14', '0', '200004');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Druide Soigneur', 'Invocation de Cairne', '', '7', '0', '1', '3001', '8356', '3001', '8356', '0', NULL, '200005');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '80', '1684', '75000', '90000', '100000', '1', '0', '1500', '0', '4678', '9843', '0', '0', '0', '36000', '150000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '6130', '0', '0', '2.5', '8', '14', '0', '200005');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Bûcheron Karbois', '', '', '7', '0', '0', '308', '308', '308', '308', '0', NULL, '200006');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('63', '67', '1684', '4500', '9000', '1000', '1', '0', '1500', '0', '1550', '2580', '0', '0', '0', '36000', '1500', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '6130', '0', '0', '2.5', '8', '14', '0', '200006');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Vibol', 'La Bombe', '', '7', '0', '3', '28859', '28859', '28859', '28859', '0', NULL, '200007');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '83', '1684', '3309250', '6309250', '100000', '1', '0', '1500', '0', '7862', '12000', '0', '0', '0', '36000', '15000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '676130', '0', '0', '2.5', '8', '14', '0', '200007');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Elune', '', '', '7', '0', '3', '17607', '17607', '17607', '17607', '0', NULL, '200001');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '80', '1683', '1000000', '10000000', '1000000', '10000', '0', '1500', '-1', '0', '0', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '2.5', '8', '14', '1', '200001');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Druide Elfe', 'Serviteur d\'Elune', '', '7', '0', '1', '21106', '21106', '21106', '21106', '0', NULL, '200002');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '80', '1684', '43560', '78903', '1000000', '10000', '0', '1500', '0', '3600', '7200', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '41656', '0', '0', '2.5', '8', '14', '0', '200002');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Garvald Dénokis', '', '', '7', '0', '3', '21106', '21106', '21106', '21106', '0', NULL, '200003');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('80', '83', '1683', '2340560', '5780903', '8996665', '10000', '0', '1500', '0', '7000', '12000', '0', '0', '0', '36000000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '1', '681656', '0', '0', '2.5', '8', '14', '0', '200003');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Rôdeur Gorfares', '', '', '7', '0', '0', '11640', '11640', '11640', '11640', '0', NULL, '200008');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('64', '67', '1684', '3620', '6520', '100000', '1', '0', '1500', '0', '700', '2000', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '8520', '0', '0', '2.5', '8', '14', '0', '200008');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Mineur Kobold', '', '', '7', '0', '0', '2153', '2153', '2153', '2153', '0', NULL, '200009');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('64', '67', '1684', '3620', '6520', '100000', '1', '0', '1500', '0', '700', '2000', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '18520', '0', '0', '2.5', '8', '14', '0', '200009');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Harpie Minbalt', '', '', '7', '0', '0', '3022', '3022', '3022', '3022', '0', NULL, '200010');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('63', '66', '1684', '4620', '4720', '100000', '1', '0', '1500', '0', '700', '2000', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '18520', '0', '0', '2.5', '8', '14', '0', '200010');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Trotteur des  Plaines', '', '', '7', '0', '0', '1283', '1283', '1283', '1283', '0', NULL, '200011');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('63', '66', '1684', '4620', '4720', '100000', '1', '0', '1500', '0', '700', '2000', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '18520', '0', '0', '2.5', '8', '14', '0', '200011');
INSERT INTO `creature_names` (`name`, `subname`, `info_str`, `type`, `family`, `rank`, `male_displayid`, `female_displayid`, `male_displayid2`, `female_displayid2`, `civilian`, `leader`, `entry`) VALUES ('Porc des Plaines', '', '', '7', '0', '0', '377', '377', '377', '377', '0', NULL, '200012');
INSERT INTO `creature_proto` (`minlevel`, `maxlevel`, `faction`, `minhealth`, `maxhealth`, `mana`, `scale`, `npcflags`, `attacktime`, `attacktype`, `mindamage`, `maxdamage`, `rangedattacktime`, `rangedmindamage`, `rangedmaxdamage`, `respawntime`, `armor`, `resistance1`, `resistance2`, `resistance3`, `resistance4`, `resistance5`, `resistance6`, `combat_reach`, `bounding_radius`, `auras`, `boss`, `money`, `invisibility_type`, `death_state`, `walk_speed`, `run_speed`, `fly_speed`, `IsTrainingDummy`, `entry`) VALUES ('63', '66', '1684', '4620', '4720', '100000', '2', '0', '1500', '0', '700', '2000', '0', '0', '0', '36000', '10000', '0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '18520', '0', '0', '2.5', '8', '14', '0', '200012');

/* On insert les Quêtes */
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '3', '1', '1', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Ramener du bois au campement.', 'Bonjours à vous voyageur, j\'ai une tache à vous confier.$BAfin de pouvoir renforcer notre QG nous avons besoin d\'un ravitaillement en bois.$B$BCependant, les bûcherons sont les seuls à avoir le matériel afin d\'en récupérer. Mais ils préfèrent vendre leurs récoltent et le fait que nous leur occupions du terrain les rendent hostile. ', 'Vous devrez donc leur voler 20 bûches solides, et de tuer 10 bûcherons hostile.$B', '', 'Vous n\'avez pas encore fini la quête, revenez une fois accompi !', 'Bravo, merci de nous avoir ravitailler !', '', '', '', '', '9000001', '0', '0', '0', '10', '0', '0', '0', '2000006', '0', '0', '0', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '51456', '380000', '0', '0', '0', '0', '0', '0', '51456', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '900001');
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '3', '60', '60', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'L\'or des Mines', 'Certaines rumeurs ébruitent notre avant-poste.$BElles parlent d\'une mine qui recèlent de pépites d\'Or. C\'est une chance inouïe, c\'est l\'occasion de pouvoir remplir la banque et de pouvoir payer nos troupes !$B$BCependant, nous n\'avons aucune idée d\'où est cachée cette mine ! On raconte qu\'elle est sur les bords de la colline la plus proche, mais c\'est tout ce nous savons.$B', 'Vous devrez donc leur voler 10 pépites d\'or, et tuer 10 Kobold.', '', 'Vous n\'avez pas encore fini la quête, revenez une fois accompi !', 'Bravo, merci de nous avoir ravitailler !', '', '', '', '', '9000002', '0', '0', '0', '10', '0', '0', '0', '2000007', '0', '0', '0', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '51456', '390000', '0', '0', '0', '0', '0', '0', '51456', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '900002');
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '1', '65', '65', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'A la chasse !', 'Le campement manque éperdument de nourriture.$BNos éclaireurs nous ont rapportés de fraîches nouvelles. Ces terres grouillent de gibiers dont la viande est très convoitée. C\'est l\'occasion de pouvoir rassasier nos troupes qui s\'affament !$B$BOffrez leur du bon temps ! ', 'Vous devrez donc récolter 5 viandes de rapace et 10 viandes de porc.', '', 'Vous n\'avez pas encore fini la quête, merci de revenir, une fois celle-ci fini !', 'Bravo, merci d\'avoir chassé pour nous, ce soir sera un festin !', '', '', '', '', '00003', '00004', '0', '0', '5', '10', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '51200', '0', '0', '0', '0', '0', '0', '0', '62510', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '900003');
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '1', '65', '65', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'A la chasse !', '$BUn ravitaillement en provenances de nos envoyés spéciaux en Norfendre, contenant des armes et des outils, a été attaqué par des harpies...$B$BVoleuse sanguinaire, sales harpies, toujours là au mauvais moment. Venons en au but, j\'ai un service à vous demander si vous l\'accepter.$B$BSi vous pouviez parcourir ces terres afin de vous aventurer dans le campement des harpies afin de retrouver les matériaux perdu, ce serait une avancée considérable dans notre ravitaillement.$B', 'Vous devrez donc récupérer la trousse à outils et la caisse d\'armes.', '', 'Vous n\'avez pas encore fini la quête, merci de revenir, une fois celle-ci fini !', 'Bravo, merci d\'avoir retrouver les materieux ! Nous vous en sommes infiniment reconnaissant !', '', '', '', '', '00005', '00006', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '51200', '380000', '0', '0', '0', '0', '0', '0', '62510', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '900004');
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '1', '65', '65', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Coffre sous-marin.', '$BUn de nos pêcheurs dit avoir vu quelque chose briller au fond de l\'eau dans le lac.$BNous pensons que c\'est le coffre perdu de Sang-Fourchu, un groupe pirates exilés de la horde-dissoute et de l\'ancienne alliance.$B$BCe coffre doit contenir un trésor immense. Pouvez vous nous ramener le contenu du trésor afin de pouvoir élargir le budget de notre clan, cela nous rendrait service !', 'Vider le coffre sous-marin', '', 'Vosu \'navez pas encore vidé le coffre, revenez une fois votre quête fini !', 'Bravo, mission accompli, vous assurez la survie de notre clan grace a vos actes !', '', '', '', '', '0000001', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '60404', '260000', '0', '0', '0', '0', '0', '0', '60143', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '900019');
INSERT INTO `quests` (`ZoneId`, `sort`, `flags`, `MinLevel`, `questlevel`, `Type`, `RequiredRaces`, `RequiredClass`, `RequiredTradeskill`, `RequiredTradeskillValue`, `RequiredRepFaction`, `RequiredRepValue`, `LimitTime`, `SpecialFlags`, `PrevQuestId`, `NextQuestId`, `srcItem`, `SrcItemCount`, `Title`, `Details`, `Objectives`, `CompletionText`, `IncompleteText`, `EndText`, `ObjectiveText1`, `ObjectiveText2`, `ObjectiveText3`, `ObjectiveText4`, `ReqItemId1`, `ReqItemId2`, `ReqItemId3`, `ReqItemId4`, `ReqItemCount1`, `ReqItemCount2`, `ReqItemCount3`, `ReqItemCount4`, `ReqKillMobOrGOId1`, `ReqKillMobOrGOId2`, `ReqKillMobOrGOId3`, `ReqKillMobOrGOId4`, `ReqKillMobOrGOCount1`, `ReqKillMobOrGOCount2`, `ReqKillMobOrGOCount3`, `ReqKillMobOrGOCount4`, `ReqCastSpellId1`, `ReqCastSpellId2`, `ReqCastSpellId3`, `ReqCastSpellId4`, `RewChoiceItemId1`, `RewChoiceItemId2`, `RewChoiceItemId3`, `RewChoiceItemId4`, `RewChoiceItemId5`, `RewChoiceItemId6`, `RewChoiceItemCount1`, `RewChoiceItemCount2`, `RewChoiceItemCount3`, `RewChoiceItemCount4`, `RewChoiceItemCount5`, `RewChoiceItemCount6`, `RewItemId1`, `RewItemId2`, `RewItemId3`, `RewItemId4`, `RewItemCount1`, `RewItemCount2`, `RewItemCount3`, `RewItemCount4`, `RewRepFaction1`, `RewRepFaction2`, `RewRepFaction3`, `RewRepFaction4`, `RewRepFaction5`, `RewRepFaction6`, `RewRepValue1`, `RewRepValue2`, `RewRepValue3`, `RewRepValue4`, `RewRepValue5`, `RewRepValue6`, `RewRepLimit`, `RewMoney`, `RewXP`, `RewSpell`, `CastSpell`, `PointMapId`, `PointX`, `PointY`, `PointOpt`, `RewardMoneyAtMaxLevel`, `ExploreTrigger1`, `ExploreTrigger2`, `ExploreTrigger3`, `ExploreTrigger4`, `RequiredOneOfQuest`, `RequiredQuest1`, `RequiredQuest2`, `RequiredQuest3`, `RequiredQuest4`, `RemoveQuests`, `ReceiveItemId1`, `ReceiveItemId2`, `ReceiveItemId3`, `ReceiveItemId4`, `ReceiveItemCount1`, `ReceiveItemCount2`, `ReceiveItemCount3`, `ReceiveItemCount4`, `IsRepeatable`, `entry`) 
VALUES ('0', '0', '2', '65', '65', '0', '1791', '1535', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', 'Tuez les intrus !', 'Certains de nos éclaireurs ne sont jamais revenus de leurs rondes. Nous ignorons encore pourquoi, mais il se peut que des centaures du clan Gorfares rodent dans les parages.$B$BSi vous pouviez en tuer au moins un histoire que nos gardes puissent continuer à nous garder en sûreté. De nombreuses personnes comptes sur eux pour assurer la survie de nos positions.$B$BRendez-nous ce service s\'il vous plaît.$B', 'Vous devrez donc tuer 1 Rôdeur Gorfare.', '', 'Vous n\'avez pas encore tué l\'intru, revenez une fois la quête terminé !', 'Bravo, mission accompli, vous assurez la survie de notre clan grace a vos actes !', '', '', '', '', '0', '0', '0', '0', '0', '0', '0', '0', '200008', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '60404', '260000', '0', '0', '0', '0', '0', '0', '60143', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '900005');
